name: lint
  # run lint flake8
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependecies
        run: |
          pip install poetry
          make install
      - name: run test and linter	
        run: make lint
